run_program:
    description: Run a defined irrigation program.
    fields:
        entity_id:
            description: The program to manually run, template evaluation is ignored.
            example: 'irrigation.morning'

run_zone:
    description: Run a defined irrigation zone.
    fields:
        entity_id:
            description: The zone to manually run, template evaluation is ignored.
            example: 'irrigation_zone.vege_patch'
        duration:
            description: Otional - Minutes to water.
            example: 1
        
stop_programs:
    description: Stop any running programs or zones.
